### ISSUE TITLE
Today is Earth Day

### ISSUE THREAD

**Issue by Smuzzy-waiii** [Smuzzy-waiii/Rainbow-Poem#4]
Today is Earth Day!, and i think the poem should reflect.

[This link](https://youtube.com) and **bold**.

![image](https://user-images.githubusercontent.com/62249539/85238563-65ffd280-b44c-11ea-95e3-e2da82b0e01d.png)

**Comment by jawalkar** [comment]
Ikrr this really should be done!!

**Comment by Smuzzy-waiii** [comment]
I guess thats enough?
